import { createSlice } from '@reduxjs/toolkit';

import { fetchAllProductsAsync } from './thunks';
import { ProductState } from './types';

const initialState: ProductState = {
  data: [],
  status: 'idle',
};

export const productSlice = createSlice({
  name: 'products',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    resetProducts: (state) => {
      state.data = [];
      state.status = 'idle';
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAllProductsAsync.pending, (state) => {
        state.status = 'pending';
      })
      .addCase(fetchAllProductsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload.data;
      });
  },
});

export default productSlice;
